# fly.toml app configuration file generated for iavian-kafka-app-name on 2025-02-26T08:18:59+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'iavian-kafka-app-name'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'kafka_data'
  destination = '/data'

[http_service]
  internal_port = 9092
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 9092

  [[services.ports]]
    port = 9092

[[services]]
  protocol = 'tcp'
  internal_port = 29092

  [[services.ports]]
    port = 29092

[[services]]
  protocol = 'tcp'
  internal_port = 29093

  [[services.ports]]
    port = 29093

[checks]
  [checks.kafka]
    port = 29092
    type = 'tcp'
    interval = '15s'
    timeout = '10s'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
